sample1: sample1.cpp
	g++ -o sample1 sample1.cpp -lpthread
sample2: sample2.cpp
	g++ -o sample2 sample2.cpp -lpthread
semdemo: semdemo.cpp
	g++ -o semdemo semdemo.cpp -lpthread
seminit: seminit.cpp
	g++ -o seminit seminit.cpp -lpthread
thread: thread.cpp
	g++ -o thread thread.cpp -lpthread